spring.application.name=Projectproject

#Data base connectivity and configuration
spring.datasource.url = jdbc:mysql://localhost:3306/projectz?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate Configuration

# this property tells hibernate to automatically create tables
spring.jpa.hibernate.ddl-auto=update
# it is used to log the sql statements that are executed by hibernateto the consloe
spring.jpa.show-sql=true